edutours/views.py
# Flask routes handling requests
from flask import Blueprint, render_template, url_for, request, session, flash, redirect, abort
from .models import City, Tour, Order
from datetime import datetime
from .forms import CheckoutForm
from . import db

main_bp = Blueprint('main', __name__)

@main_bp.route('/')
def index():
    cities = db.session.scalars(db.select(City).order_by(City.id)).all()
    return render_template('index.html', cities=cities)

@main_bp.route('/city/<int:city_id>/')
def city(city_id):
    cities = db.session.scalars(db.select(City).order_by(City.id)).all()
    tours = db.session.scalars(db.select(Tour).where(Tour.city_id == city_id)).all()
    selected_city = db.session.get(City, city_id)
    return render_template('city.html', cities=cities, tours=tours, city=selected_city)

@main_bp.route('/tour/<int:tour_id>/')
def tour(tour_id):
    cities = db.session.scalars(db.select(City).order_by(City.id)).all()
    tour_info = db.session.get(Tour, tour_id)
    return render_template('tour.html', cities=cities, tour=tour_info)

@main_bp.route('/order', methods=['GET', 'POST'])
def order():
    cities = db.session.scalars(db.select(City).order_by(City.id)).all()
    tour_id = request.values.get('tour_id')
    print(f'Values: {tour_id}')
    # Check if there is an existing order Id 
    if 'order_id' in session.keys():
        order = db.session.scalar(db.select(Order).where(Order.id==session['order_id']))
    else:
        order = None

    # If not, create new order
    if order is None:
        order = Order(status=False, first_name='', surname='', email='', phone='', total_cost=0.00, date=datetime.now())
        try:
            db.session.add(order)
            db.session.commit()
            session['order_id'] = order.id
        except:
            print('Failed trying to create a new order!')
            order = None
    
    # Calculate total price
    total_price = 0
    if order is not None:
        for tour in order.tours:
            total_price += tour.price
    
    # Are we adding an item?
    if tour_id is not None and order is not None:
        tour = db.session.scalar(db.select(Tour).where(Tour.id==tour_id))
        try:
            order.tours.append(tour)
            for tour in order.tours:
                total_price += tour.price
            order.total_cost = total_price
            db.session.commit()
        except:
            flash('There was an issue adding the item to your basket', category='danger')
        return redirect(url_for('main.order'))
    return render_template('order.html', cities=cities, order=order, total_price=total_price)

@main_bp.route('/deleteorderitem', methods=['POST'])
def deleteorderitem():
    id = request.form['id']
    print(f'Tour to delete ID is: {id}')
    if 'order_id' in session:
        order = db.session.scalar(db.select(Order).where(Order.id==session['order_id']))
        if not order:
            flash("There's no order to delete!")
            return redirect(request.referrer)
        print(order.tours)
        tour_to_delete = db.session.scalar(db.select(Tour).where(Tour.id==id))
        print(f'Deleting: {tour_to_delete.name}')
        try:
            tour_to_delete.qty = 0
            order.tours.remove(tour_to_delete)
            db.session.commit()
        except:
            print('Something went wrong when trying to delete the order')
            abort(500)
    return redirect(url_for('main.order'))

# Empty basket
@main_bp.route('/deleteorder')
def deleteorder():
    if 'order_id' in session:
        order = db.session.scalar(db.select(Order).where(Order.id==session['order_id']))
        for tour in order.tours:
            order.tours.remove(tour)
        session.pop('order_id')
        db.session.commit()
        flash('Basket emptied!')
    else:
        flash("There's no order to delete!")
        return redirect(request.referrer)
    return redirect(url_for('main.order'))

# Complete the order
@main_bp.route('/checkout', methods=['GET', 'POST'])
def checkout():
    form = CheckoutForm() 
    if 'order_id' in session:
        order = db.session.scalar(db.select(Order).where(Order.id==session['order_id']))
        if not order.tours:
            flash('You need to add some tours to your basket first!')
            return(redirect(request.referrer))
        if form.validate_on_submit():
            order.status = True
            order.first_name = form.firstname.data
            order.surname = form.surname.data
            order.email = form.email.data
            order.phone = form.phone.data
            total_cost = 0
            for tour in order.tours:
                total_cost += (tour.price * 1)
            order.total_cost = total_cost
            order.date = datetime.now()
            try:
                db.session.commit()
                deleteorder()
                flash('Thank you! One of our team members will contact you soon.')
                return redirect(url_for('main.index'))
            except:
                flash('There was an issue completing your order')
                return (redirect(request.referrer))
    return render_template('checkout.html', form=form)

@main_bp.route("/search", methods=['GET','POST'])
def search():
    cities = db.session.scalars(db.select(City).order_by(City.id)).all()
    search_query = f'%{request.args.get('search')}%'
    tours = db.session.scalars(db.select(Tour).where(Tour.description.like(search_query)))
    return render_template('city.html', cities=cities, tours=tours)

edutours/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Travel and Learn in Taiwan</title>

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
    integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
</head>

<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{{url_for('main.index')}}">Travel & Learn In Taiwan</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{{url_for('main.index')}}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
              City In Formosa
            </a>
            <div class="dropdown-menu">
              {% for city in cities %}
                <a class="dropdown-item" href="/city/{{ city.id }}">{{ city.name }}</a>
              {% endfor %}
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('main.order')}}">Order</a>
          </li>
          </li>
        </ul>
        <ul class="nav navbar-nav ml-auto">
          <li class="nav-item">
              <form class="form-inline my-2 my-lg-0 ml-5" action="{{url_for('main.search')}}">
                  <input class="form-control" name="search" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-black btn btn-primary btn-s my-0 ml-1" type="submit">Search</button>
              </form>
          </li>
      </ul>
      </div>
    </nav>

    {% block head %}

    {% endblock %}
  </header>

  <main class="container">
    {% block main %}
            
    {% endblock %}
  </main>

  <footer class="footer mt-5">
    <div class="text-center py-2 bg-primary">
      <span class="text-light">Copyright &copy; 2024</span>
    </div>
  </footer>

  <!-- Bootstrap JS -->
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct"
    crossorigin="anonymous"></script>
</body>

</html>

edutours/templates/checkout.html
{% extends 'base.html' %} {% from 'bootstrap4/form.html' import render_form %}
{% block main %}
<div class="row justify-content-center">
  <div class="col-12 col-lg-6">
    <h1 class="my-5 text-center">Checkout</h1>
    <p class="mb-5">
      Please provide your details so that we can contact you to finalise details
      and take payment. Thank you!
    </p>
    <div>{{render_form(form)}}</div>
  </div>
</div>
{% endblock %}

edutours/templates/city.html
{% extends 'base.html' %} {% block head %} {% if city %}
<div
  class="jumbotron text-center jumbotron_bg"
  style="background-image: url('{{ url_for('static', filename= 'img/' + city.image) }}');"
>
  <h1 class="display-4">Discovery {{ city.name }}</h1>
  <p class="lead">{{ city.description }}</p>
</div>
{% else %}
<h1 class="text-center my-5">Search Results</h1>
{% endif %} {% endblock %} {% block main %}
<div class="row mt-5">
  {% for tour in tours%}
  <div class="col-12 col-sm-6 col-lg-4 mb-4">
    <div class="card">
      <img
        src="{{url_for('static', filename='img/' + tour.image)}}"
        class="card-img-top"
        alt="{{ tour.name }}"
      />
      <div class="card-body d-flex flex-column justify-space-around">
        <h5 class="card-title">{{ tour.name }}</h5>
        <p class="card-text limited_text">{{ tour.description }}</p>
        <a
          href="/tour/{{tour.id }}"
          class="btn btn-outline-primary btn-block"
          >Read More</a
        >
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

edutours/templates/error.html
{% extends 'base.html' %}

{% block main %}
<div class="container text-center">
    <h1 class="mt-5 text-center">Error</h1>
    <p>Sorry, but something went wrong!</p>
    <a href="{{url_for('main.index')}}" class="btn btn-primary">Go to home page</a>
</div>
{% endblock %}

edutours/templates/index.html
{% extends 'base.html' %} {% block head %}
<div class="jumbotron text-center jumbotron_bg index_jumbotron">
  <h1 class="display-4">Discovery Taiwan Cuisine</h1>
  <p class="lead">
    Visit Taiwan and learn how to cook Taiwanese cuisine. <br />
    Traveling and learning at the same time.
  </p>
</div>
{% endblock %} {% block main %}
<h1 class="my-5 text-center">Top 3 Cities</h1>
<div class="row">
  {% for city in cities%}
  <div class="col-12 col-sm-6 col-lg-4 mb-4">
    <div class="card">
      <img
        src="{{url_for('static', filename='img/' + city.image )}}"
        class="card-img-top"
        alt="{{ city.name }}"
      />
      <div class="card-body d-flex flex-column justify-space-around">
        <h5 class="card-title">{{ city.name }}</h5>
        <p class="card-text">{{ city.description }}</p>
        <a
          href="/city/{{ city.id }}"
          class="btn btn-outline-primary btn-block"
          >Find Tours</a
        >
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

edutours/templates/order.html
{% extends 'base.html' %} {% block main %}
<section>
  <div class="container">
    <h1 class="text-center my-5">Shopping Basket</h1>

    {% if order.tours | length == 0 %}
    <p class="text-center">No tours selected yet.</p>
    <div class="row justify-content-center">
      <a
        href="{{url_for('main.index')}}"
        class="btn btn-primary"
        >Find Tours</a
      >
    </div>
    {% else %} {% for tour in order.tours %}
    <div class="card mb-3 order_page">
      <div class="row no-gutters">
        <div class="col-lg-4 col-12">
          <img
            class="card-img-top"
            class="img-thumbnail"
            src="{{url_for('static', filename=('img/' + tour.image))}}"
          />
        </div>
        <div class="col-lg-8 col-12">
          <div class="card-body">
            <h5 class="card-title">
              {{tour.name}} in {{tour.city.name}} city |
              <strong>{{tour.date.strftime("%d/%m/%Y")}}</strong>
            </h5>
            <p class="card-text">{{tour.description}}</p>
          </div>
          <div class="card-body d-flex justify-content-between align-itmes-end">
            <h5 class="mt-2">{{"$%.2f"|format(tour.price)}} Per Person</h5>
            <form
              method="POST"
              action="{{url_for('main.deleteorderitem')}}"
            >
              <input
                type="hidden"
                id="id"
                name="id"
                value="{{tour.id}}"
              />
              <input
                type="submit"
                value="Delete"
                class="btn btn-primary"
              />
            </form>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
    <div class="row">
      <div class="col-12 d-flex justify-content-end">
        <h5 class="mt-4">Quote = {{"$%.2f"|format(total_price)}}</h5>
      </div>
      <div class="col-12 d-flex mt-2 mb-4 justify-content-end">
        <a
          href="{{url_for('main.deleteorder')}}"
          class="btn btn-primary"
          >Empty Basket</a
        >
        <a
          href="{{url_for('main.checkout')}}"
          class="btn btn-primary ml-4"
          >Checkout</a
        >
      </div>
    </div>
    {% endif %}
  </div>
</section>

{% endblock %}

edutours/templates/tour.html
{% extends 'base.html' %} {% block main %}
<div class="row">
  <div class="row detail_box">
    <div class="col-12 col-sm-6">
      <img
        src="{{url_for('static', filename = 'img/'+tour.image)}}"
        class="rounded img-fluid"
        alt="{{tour.name}}}"
      />
    </div>
    <div class="col-12 col-sm-6 d-flex flex-column">
      <h3>{{tour.name}}</h3>
      <div class="desc pb-3">{{tour.description}}</div>
      <div class="">
        A meal included: {% if tour.has_meal %}
        <span>Yes</span>
        {% else %}
        <span>No</span>
        {% endif %}
      </div>
      <div class="">Language offered: {{ tour.languages }}</div>
      <div class="">Price: ${{tour.price}}/per person</div>
      <form
        class="mt-3"
        action="{{url_for('main.order')}}"
      >
        <input
          type="hidden"
          id="tour_id"
          name="tour_id"
          value="{{tour.id}}"
        />
        <input
          class="d-block btn btn-primary"
          type="submit"
          value="Add to cart"
        />
      </form>
    </div>
  </div>
</div>
{% endblock %}